package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
)

// xorKey 是 Anti-Glance 混淆的静态密钥（防杀软静态只读段特征扫描）
var xorKey = []byte{0x78, 0x41, 0x6E, 0x74, 0x69, 0x47, 0x6C, 0x61, 0x6E, 0x63, 0x65} // "xAntiGlance"

var targetFiles = []string{
	"data/prompt-v2.1.md",
	"data/prompt-v2.md",
	"data/prompt-ctf-scoring.md",
	"data/tamper_rules.txt",
	"data/rewrite_prompt.txt",
	"data/qa.json",
}

func main() {
	// 查找 internal/assets 路径
	baseDir := filepath.Join("internal", "assets")
	if _, err := os.Stat(filepath.Join(baseDir, "data")); err != nil {
		if _, err := os.Stat("data"); err == nil {
			baseDir = "."
		} else {
			baseDir = filepath.Join("..", "..", "internal", "assets")
		}
	}

	var buf bytes.Buffer
	buf.WriteString("// Code generated by tools/genassets; DO NOT EDIT.\n\n")
	buf.WriteString("package assets\n\n")
	buf.WriteString("// xorKey 是 Anti-Glance 异或混淆密钥，防杀毒软件扫描只读数据段（.rdata）误报。\n")
	buf.WriteString("var xorKey = []byte{")
	for i, b := range xorKey {
		if i > 0 {
			buf.WriteString(", ")
		}
		buf.WriteString(fmt.Sprintf("0x%02x", b))
	}
	buf.WriteString("}\n\n")

	buf.WriteString("// obfuscatedData 存储经 XOR 混淆后的资产数据字节流。\n")
	buf.WriteString("var obfuscatedData = map[string][]byte{\n")

	for _, relPath := range targetFiles {
		fullPath := filepath.Join(baseDir, relPath)
		raw, err := os.ReadFile(fullPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "error reading %s: %v\n", fullPath, err)
			os.Exit(1)
		}

		// 执行 XOR 混淆
		encoded := make([]byte, len(raw))
		for i, b := range raw {
			encoded[i] = b ^ xorKey[i%len(xorKey)]
		}

		// 标准化 map key，统一为正斜杠相对路径（如 "data/prompt-v2.1.md"）
		key := filepath.ToSlash(relPath)
		buf.WriteString(fmt.Sprintf("\t%q: {\n\t\t", key))
		for i, b := range encoded {
			buf.WriteString(fmt.Sprintf("0x%02x, ", b))
			if (i+1)%16 == 0 && i+1 < len(encoded) {
				buf.WriteString("\n\t\t")
			}
		}
		buf.WriteString("\n\t},\n")
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "error formatting generated Go code: %v\n", err)
		os.Exit(1)
	}

	outPath := filepath.Join(baseDir, "data_gen.go")
	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		fmt.Fprintf(os.Stderr, "error writing %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("Successfully generated obfuscated assets to %s (%d files)\n", outPath, len(targetFiles))
}
